http://localhost:4000/
###
POST http://localhost:4000/blocks
Content-Type: application/json
###
 http://localhost:4000/blocks
###
http://localhost:4000/blocks/295fbf0bdf7df12a4f1bf2d9a55a5de294fad91588473c2353a2511e5155c109
###
http://localhost:4000/status
###
POST http://localhost:4000/transactions
Content-Type: application/json

{
  "to" : "lynn",
  "amount" : 50
}
###
http://localhost:4000/balance/nico
####
http://localhost:4000/balance/nico?total=true
###
http://localhost:4000/mempool
###
http://localhost:4000/balance/lynn
###
http://localhost:4000/wallet
###
http://localhost:4000/balance/755bf1006d8763c12819a0d5545793018a3bbd2159cab2413cc55906bd0980c3b132153484e93e27604af2a465ff3272c1f399e14802dadfa1e84ee389b17031
###
http://localhost:4000/balance/lynn
